### ISSUE TITLE
netrw_altfile option

### ISSUE THREAD

**Issue by tomdaniels** [prichrd/netrw.nvim#32]
hey thanks for maintaining this plugin, more of a question than an issue hope you don't mind, `vim.g.netrw_altfile = 1` can be used to keep netrw out of the alt file `ctrl-^` list, but since adding this plugin it seems to not be respected.

I am using lazy vim with the default config

```lua
-- /lua/lazy/netrw.lua
return {
  "prichrd/netrw.nvim",
  init = function ()
    vim.g.netrw_altfile = 1
  end,
  config = function ()
    require("netrw").setup()
  end
}
```

if i execute `:lua print(vim.g.netrw_altfile)` it prints 1 as I expect but only keeps netrw out of the altfile list if I don't load this plugin and just use the default netrw, which is why I'm looking at this plugin to be the culprit, so just curious really is this known about/ignored intentionally or a maaaajor skill issue 😇 ?

**Comment by prichrd** [comment]
Hey @tomdaniels,

Thank you for raising the issue, I’m happy to help with any questions/problems. I’ve tried reproducing the issue with a few configurations and wonder if you’re experiencing a netrw bug. It looks like the `netrw_altfile` option isn’t respected when the netrw buffer is the first one opened; I got consistent results with and without the plugin.

`ctrl-^` opens the alt buffer, when the netrw buffer isn't the first one opened:
- `nvim —clean` (without plugin installed) and `nvim` (with plugin installed)
- `:lua vim.g.netrw_altfile = 1`
- `:e buf-a`
- `:Ex` and select another buffer
- `ctrl-^` opens `buf-a`

`ctrl-^` opens the netrw buffer, ignoring the option, when it’s the first opened buffer:
- `nvim —clean` (without plugin installed) and `nvim` (with plugin installed)
- `:lua vim.g.netrw_altfile = 1`
- `:Ex` and select another buffer
- `ctrl-^` opens the netrw buffer

Could you validate that this is indeed the issue? If not, could you share a reproducible procedure so that we can investigate?

**Comment by tomdaniels** [comment]
Thanks @prichrd appreciate it,

I was hoping that'd be it initially but no matter how many buffers i open before netrw it's still included in the alt list. Though if you've been able to validate scenario A there where netrw isn't the first buffer opened and can go back to `buf-a` as we expect then it can't be this plugin and I'll have to work around it. 

So yeah if you haven't been able to replicate feel free to close this and i'll keep chugging along

**Comment by prichrd** [comment]
@tomdaniels, out of curiosity, what version of nvim are you running? I ran the previous tests on:
```
$ nvim --version
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
```

**Comment by tomdaniels** [comment]
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info

```

I've been meaning to remove linuxbrew from my system, maybe this is the catalyst I need to upgrade and build it from source instead.

**Comment by tomdaniels** [comment]
so after building from scratch I thought the issue still persisted but I think i found the scenario.
Incase your insterested, with `vim.g.netrw_altfile = 1 ` and this plugin installed, if you open netrw and select a file to open a new buffer, toggling between alt files does not include netrw. 

I suspect this is infact a netrw problem because what I was doing when testing was closing the netrw buffer with `:bdelete`, not selecting a file to open, in this scenario, using `ctrl-^`  will infact take you back to nertw. 

The difference causing my bug was selecting a file to open versus closing the netrw buffer. I don't think this would be by design but something the community may have already been living with for quite sometime

**Comment by tomdaniels** [comment]
also closing this since its a non-issue for this plugin, thanks for getting back to me regardless ✌️
